
query getFimPeople {
  	allFilms(first: 5) {
    	edges {
        cursor
        node {
          title,
          director,
    			characterConnection(first: 5) {
            edges {
              cursor
              node {
                name
                species {
                  name
                  classification
                }
              }
            }
          }
        }
      }
  }
}



query getPagableFimPeople {
    allFilms(first: 5) {
        pageInfo {
            endCursor
            hasNextPage
            hasPreviousPage
            startCursor
        }
        edges {
          cursor
            node {
                title,
                director,
                characterConnection(first: 5) {
                    pageInfo {
                        hasNextPage
                        endCursor
                    }
                    edges {
                      cursor
                      node {
                          name
                          species {
                              name
                              classification
                          }
                      }
                    }
                }
            }
        }
    }
}
