type Query {
  oneOfEverything: OneOfEverything,
  viewer: AccountUserType,
  meters: [Meter]
}


# User objects are the core of the authentication system. They typically represent a customer who manages a portfolio of one or more accounts.
type AccountUserType {
  id: ID!

  # List of accounts that the user is linked to either via portfolio role or account role.
  accounts(
    # Optionally filter the user's accounts to only return those linked to portfolios on the specified brands.
    # allowedBrandCodes: [BrandChoices]

    # Optionally restrict user accounts to only return those linked to portfolios on public facing brands.
    restrictToPublicFacingBrands: Boolean

    # Optionally restrict user accounts to only return those with the specified account numbers.
    restrictToAccountNumbers: [String]

    # Optionally exclude accounts with any of the given account types.
    # excludeAccountTypes: [AccountTypeChoices]

    # Optionally exclude accounts that have never had an agreement.
    excludeAccountsWithoutAgreements: Boolean
  ): [AccountInterface]
}



enum AccountStatus {
  # A pending account is one that has been created but no registrations have started.
  PENDING

  # Account requires processes to be completed before supply can be set up
  INCOMPLETE

  # Withdrawn before supply started
  WITHDRAWN

  # Supply could have started, be ongoing or ended.
  ACTIVE

  # An error occurred when we tried to enroll a meter point. This may be deprecated in future in favour of exposing this through enrollment property of a meter point.
  ENROLMENT_ERROR

  # Meter point enrollment was rejected. This may be deprecated in future in favour of exposing this through enrollment property of a meter point.
  ENROLMENT_REJECTED

  # Dormant. Users should not be able to log into dormant accounts.
  DORMANT

  # Void. Account created in error.
  VOID
}

interface AccountInterface {
  # The brand of the account.
  brand: String

  # The current status of the account.
  status: AccountStatus

  # The current account balance.
  balance(
    # If this variable is set to true, the balance will be calculated based on the sum of balances on all ledgers configured to contribute to this account's balance. Otherwise, only the main ledger's balance will be fetched (legacy behaviour). If you are unsure, set this value to true.
    includeAllLedgers: Boolean = false
  ): Int!

  # The current account overdue balance.
  overdueBalance: Int

  # A code that uniquely identifies the account.
  number: String
}

type OneOfEverything {
    # Required ID
    id: ID!,

    # Required date
    # date: Date!,

    # Required DateTime
    # dateTime: DateTime!,

    # Required String
    string: String!,

    # Required Int
    amount: Int!,

    # Required Float
    float: Float!,

    # Required Boolean
    boolean: Boolean!,

    # Optional ID
    optionalId: ID,

    # Optional date
    # optionalDate: Date,

    # Optional DateTime
    # optionalDateTime: DateTime,

    # Optional String
    optionalString: String,

    # Optional Int
    optionalAmount: Int,

    # Optional Float
    optionalFloat: Float,

    # Optional Boolean
    optionalBoolean: Boolean,

    # Array of Int
    arrayOfInt: [Int],

    # Array of Required Int
    arrayOfRequiredInt: [Int!],

    child: [OneOfEverything]
}


"""An object with an ID"""
interface Node {
  """The id of the object."""
  id: ID!
}

"""A single film."""
type Film implements Node {

  """The ISO 8601 date format of the time that this resource was created."""
  created: String

  """The name of the director of this film."""
  director: String

  """The ISO 8601 date format of the time that this resource was edited."""
  edited: String

  """The episode number of this film."""
  episodeID: Int

  """The ID of an object"""
  id: ID!

  """The opening paragraphs at the beginning of this film."""
  openingCrawl: String
}



interface Meter {
  id: ID!
  serialNumber: String!
}

type GasMeter implements Meter {
  id: ID!
  serialNumber: String!
  mprn: String
}

type ElectricityMeter implements Meter {
  id: ID!
  serialNumber: String!
  mpan: String
}
