[package]
name = "sparko_graphql_derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
sparko_graphql_core = { version = "0.1.0", path = "../sparko_graphql_core" }
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0.86"
proc-macro-error = "1.0"
inflections = "1.1.1"
deluxe = "0.5.0"